site_name: Jupyter-TikZ
repo_url: https://github.com/lucaslrodri/jupyter-tikz

theme:
  name: material
  logo: assets/logo.svg
  palette:
    primary: white
    accent: custom
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.footer

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage: usage/index.md
  - Arguments reference: arguments.md
  - API reference: api.md
  - Development guide: development.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - macros
