name: Test Python package

on: [push, pull_request]

jobs:
  test: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX and Poppler
        run: |
          sudo apt update
          sudo apt install -y texlive-latex-extra texlive-luatex poppler-utils
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --without doc

      - name: Run tests
        run: |
          poetry run task test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}